language: node_js
os: linux
node_js:
   - "stable"
cache:
   directories:
      - node_modules
script:
   - CI="" npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
